include("Sol_cost.jl")

cwd = pwd()
inst_names = readdir(cwd*"\\data 2")

for (index,inst) in enumerate(inst_names)
    println("instance :",inst)
    sol = generate_solution(inst)
end 

#sol = parse("10_ulysses_3.tsp")
#sol = parse("10_ulysses_6.tsp")
#sol = parse("10_ulysses_9.tsp") 
#sol = parse("14_burma_3.tsp")
#sol = parse("14_burma_6.tsp")
#sol = parse("14_burma_9.tsp")
#sol = parse("22_ulysses_3.tsp")
#sol = parse("22_ulysses_6.tsp")
#sol = parse("22_ulysses_9.tsp")
#sol = parse("26_eil_3.tsp")
#sol = parse("26_eil_6.tsp")
#=sol = parse("26_eil_9.tsp")
sol = parse("30_eil_3.tsp")
sol = parse("30_eil_6.tsp")
sol = parse("30_eil_9.tsp")
sol = parse("34_pr_3.tsp")
sol = parse("34_pr_6.tsp")
sol = parse("34_pr_9.tsp")
sol = parse("38_rat_3.tsp")
sol = parse("38_rat_6.tsp")
sol = parse("38_rat_9.tsp")
sol = parse("40_eil_3.tsp")
sol = parse("40_eil_6.tsp")
sol = parse("40_eil_9.tsp")
sol = parse("44_lin_3.tsp")
sol = parse("44_lin_6.tsp")
sol = parse("44_lin_9.tsp")
sol = parse("48_att_3.tsp")
sol = parse("48_att_6.tsp")
sol = parse("48_att_9.tsp")
sol = parse("52_berlin_3.tsp")
sol = parse("52_berlin_6.tsp")
sol = parse("52_berlin_9.tsp")
sol = parse("70_st_3.tsp")
sol = parse("70_st_6.tsp")
sol = parse("70_st_9.tsp")
sol = parse("80_gr_3.tsp")
sol = parse("80_gr_6.tsp")
sol = parse("80_gr_9.tsp")
sol = parse("100_kroA_3.tsp")
sol = parse("100_kroA_6.tsp")
sol = parse("100_kroA_9.tsp")
sol = parse("202_gr_3.tsp")
sol = parse("202_gr_6.tsp")
sol = parse("202_gr_9.tsp")
sol = parse("318_lin_3.tsp")
sol = parse("318_lin_6.tsp")
sol = parse("318_lin_9.tsp")
sol = parse("400_rd_3.tsp")
sol = parse("400_rd_6.tsp")
sol = parse("400_rd_9.tsp")
sol = parse("532_att_3.tsp")
sol = parse("532_att_6.tsp")
sol = parse("532_att_9.tsp") =#

#= real_sol!(sol)
print_sets(sol)
println("B=",sol.B)
println(sol.cost)
println(sol.vy)

robust_model(sol) =#

#= heur_sol = vns(sol)
print_sets(heur_sol)
println(heur_sol.cost)  =#



#dualisation("data 2/10_ulysses_3.tsp")
